src/Entity/HomeText.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HomeTextRepository")
 */
class HomeText
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TituloPrincipalEs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TituloPrincipalEn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $SubtituloPrincipalEs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $SubtituloPrincipalEn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $SobreNosotrosTituloEs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $SobreNosotrosTituloEn;

    /**
     * @ORM\Column(type="text")
     */
    private $SobreNosotrosTextoEs;

    /**
     * @ORM\Column(type="text")
     */
    private $SobreNosotrosTextoEn;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $VideoLink;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ReservaTituloEs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ReservaTituloEn;

    /**
     * @ORM\Column(type="text")
     */
    private $ReservaTextoEs;

    /**
     * @ORM\Column(type="text")
     */
    private $ReservaTextoEn;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTituloPrincipalEs(): ?string
    {
        return $this->TituloPrincipalEs;
    }

    public function getTituloPrincipal($locale): ?string
    {
      if($locale === 'es')
        return $this->TituloPrincipalEs;
      return $this->TituloPrincipalEn;
    }

    public function setTituloPrincipalEs(string $TituloPrincipalEs): self
    {
        $this->TituloPrincipalEs = $TituloPrincipalEs;

        return $this;
    }

    public function getTituloPrincipalEn(): ?string
    {
        return $this->TituloPrincipalEn;
    }

    public function setTituloPrincipalEn(string $TituloPrincipalEn): self
    {
        $this->TituloPrincipalEn = $TituloPrincipalEn;

        return $this;
    }

    public function getSubtituloPrincipalEs(): ?string
    {
        return $this->SubtituloPrincipalEs;
    }

    public function getSubtituloPrincipal($locale): ?string
    {
        if($locale === 'es')
        return $this->SubtituloPrincipalEs;
        return  $this->SubtituloPrincipalEn;
    }

    public function setSubtituloPrincipalEs(string $SubtituloPrincipalEs): self
    {
        $this->SubtituloPrincipalEs = $SubtituloPrincipalEs;

        return $this;
    }

    public function getSubtituloPrincipalEn(): ?string
    {
        return $this->SubtituloPrincipalEn;
    }

    public function setSubtituloPrincipalEn(string $SubtituloPrincipalEn): self
    {
        $this->SubtituloPrincipalEn = $SubtituloPrincipalEn;

        return $this;
    }

    public function getSobreNosotrosTituloEs(): ?string
    {
        return $this->SobreNosotrosTituloEs;
    }
    public function getSobreNosotrosTitulo($locale): ?string
    {
      if($locale === 'es')
        return $this->SobreNosotrosTituloEs;
        return $this->SobreNosotrosTituloEn;
    }

    public function setSobreNosotrosTituloEs(string $SobreNosotrosTituloEs): self
    {
        $this->SobreNosotrosTituloEs = $SobreNosotrosTituloEs;

        return $this;
    }

    public function getSobreNosotrosTituloEn(): ?string
    {
        return $this->SobreNosotrosTituloEn;
    }

    public function setSobreNosotrosTituloEn(string $SobreNosotrosTituloEn): self
    {
        $this->SobreNosotrosTituloEn = $SobreNosotrosTituloEn;

        return $this;
    }

    public function getSobreNosotrosTextoEs(): ?string
    {
        return $this->SobreNosotrosTextoEs;
    }
    public function getSobreNosotrosTexto($locale): ?string
    {
      if($locale === 'es')
        return $this->SobreNosotrosTextoEs;
        return $this->SobreNosotrosTextoEn;
    }

    public function setSobreNosotrosTextoEs(string $SobreNosotrosTextoEs): self
    {
        $this->SobreNosotrosTextoEs = $SobreNosotrosTextoEs;

        return $this;
    }

    public function getSobreNosotrosTextoEn(): ?string
    {
        return $this->SobreNosotrosTextoEn;
    }

    public function setSobreNosotrosTextoEn(string $SobreNosotrosTextoEn): self
    {
        $this->SobreNosotrosTextoEn = $SobreNosotrosTextoEn;

        return $this;
    }

    public function getVideoLink(): ?string
    {
        return $this->VideoLink;
    }

    public function setVideoLink(?string $VideoLink): self
    {
        $this->VideoLink = $VideoLink;

        return $this;
    }

    public function getReservaTituloEs(): ?string
    {
        return $this->ReservaTituloEs;
    }
    public function getReservaTitulo($locale): ?string
    {
      if($locale === 'es')
        return $this->ReservaTituloEs;
        return $this->ReservaTituloEn;

    }

    public function setReservaTituloEs(string $ReservaTituloEs): self
    {
        $this->ReservaTituloEs = $ReservaTituloEs;

        return $this;
    }

    public function getReservaTituloEn(): ?string
    {
        return $this->ReservaTituloEn;
    }

    public function setReservaTituloEn(string $ReservaTituloEn): self
    {
        $this->ReservaTituloEn = $ReservaTituloEn;

        return $this;
    }

    public function getReservaTextoEs(): ?string
    {
        return $this->ReservaTextoEs;
    }

    public function getReservaTexto($locale): ?string
    {
      if($locale === 'es')
        return $this->ReservaTextoEs;
        return $this->ReservaTextoEn;
    }

    public function setReservaTextoEs(string $ReservaTextoEs): self
    {
        $this->ReservaTextoEs = $ReservaTextoEs;

        return $this;
    }

    public function getReservaTextoEn(): ?string
    {
        return $this->ReservaTextoEn;
    }

    public function setReservaTextoEn(string $ReservaTextoEn): self
    {
        $this->ReservaTextoEn = $ReservaTextoEn;

        return $this;
    }
}

src/Entity/Traits/ImageFieldTrait.php
<?php

namespace App\Entity\Traits;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Image
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
trait ImageFieldTrait
{
    public function getImagePath(){
        return 'uploads/images/'.$this->getImage()->getName();
    }

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="images", fileNameProperty="image")
     *
     * @var File
     */
    protected $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    protected $image;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTime
     */
    protected $updatedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alternativeText;

    /**
     * @return mixed
     */
    public function getAlternativeText()
    {
        return $this->alternativeText;
    }

    /**
     * @param mixed $alternativeText
     */
    public function setAlternativeText($alternativeText): void
    {
        $this->alternativeText = $alternativeText;
    }



    public function __construct()
    {
//        $this->image = new EmbeddedFile();
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|UploadedFile $imageFile
     */
    public function setImageFile(File $imageFile = null)
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt ? $this->updatedAt : new \DateTime();
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function updateModificationDate()
    {
        $this->setUpdatedAt(new \DateTime());
    }


}

templates/frontend/components/index/__special_newyear_lightrope.html.twig
<ul class="lightrope">
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
</ul>
<style type="text/css">
  .lightrope {
  text-align: center;
  white-space: nowrap;
  overflow: hidden;
  position: absolute;
  z-index: 1;
  margin: -15px 0 0 0;
  padding: 0;
  pointer-events: none;
  width: 100%;
}
.lightrope li {
  position: relative;
  -webkit-animation-fill-mode: both;
          animation-fill-mode: both;
  -webkit-animation-iteration-count: infinite;
          animation-iteration-count: infinite;
  list-style: none;
  margin: 0;
  padding: 0;
  display: block;
  width: 7px;
  height: 16px;
  border-radius: 50%;
  margin: 18px;
  display: inline-block;
  background: #00f7a5;
  box-shadow: 0px 4.6666666667px 22px 3px #00f7a5;
  -webkit-animation-name: flash-1;
          animation-name: flash-1;
  -webkit-animation-duration: 2s;
          animation-duration: 2s;
}
.lightrope li:nth-child(2n+1) {
  background: cyan;
  box-shadow: 0px 4.6666666667px 24px 3px rgba(0, 255, 255, 0.5);
  -webkit-animation-name: flash-2;
          animation-name: flash-2;
  -webkit-animation-duration: 0.4s;
          animation-duration: 0.4s;
}
.lightrope li:nth-child(4n+2) {
  background: #f70094;
  box-shadow: 0px 4.6666666667px 24px 3px #f70094;
  -webkit-animation-name: flash-3;
          animation-name: flash-3;
  -webkit-animation-duration: 1.1s;
          animation-duration: 1.1s;
}
.lightrope li:nth-child(odd) {
  -webkit-animation-duration: 1.8s;
          animation-duration: 1.8s;
}
.lightrope li:nth-child(3n+1) {
  -webkit-animation-duration: 1.4s;
          animation-duration: 1.4s;
}
.lightrope li:before {
  content: "";
  position: absolute;
  background: #222;
  width: 5px;
  height: 9.3333333333px;
  border-radius: 3px;
  top: -4.6666666667px;
  left: 1px;
}
.lightrope li:after {
  content: "";
  top: -18px;
  left: 2px;
  position: absolute;
  width: 52px;
  height: 18.6666666667px;
  border-bottom: solid #222 2px;
  border-radius: 50%;
}
.lightrope li:last-child:after {
  content: none;
}
.lightrope li:first-child {
  margin-left: -40px;
}

@-webkit-keyframes flash-1 {
  0%, 100% {
    background: #00f7a5;
    box-shadow: 0px 4.6666666667px 24px 3px #00f7a5;
  }
  50% {
    background: rgba(0, 247, 165, 0.4);
    box-shadow: 0px 4.6666666667px 24px 3px rgba(0, 247, 165, 0.2);
  }
}

@keyframes flash-1 {
  0%, 100% {
    background: #00f7a5;
    box-shadow: 0px 4.6666666667px 24px 3px #00f7a5;
  }
  50% {
    background: rgba(0, 247, 165, 0.4);
    box-shadow: 0px 4.6666666667px 24px 3px rgba(0, 247, 165, 0.2);
  }
}
@-webkit-keyframes flash-2 {
  0%, 100% {
    background: cyan;
    box-shadow: 0px 4.6666666667px 24px 3px cyan;
  }
  50% {
    background: rgba(0, 255, 255, 0.4);
    box-shadow: 0px 4.6666666667px 24px 3px rgba(0, 255, 255, 0.2);
  }
}
@keyframes flash-2 {
  0%, 100% {
    background: cyan;
    box-shadow: 0px 4.6666666667px 24px 3px cyan;
  }
  50% {
    background: rgba(0, 255, 255, 0.4);
    box-shadow: 0px 4.6666666667px 24px 3px rgba(0, 255, 255, 0.2);
  }
}
@-webkit-keyframes flash-3 {
  0%, 100% {
    background: #f70094;
    box-shadow: 0px 4.6666666667px 24px 3px #f70094;
  }
  50% {
    background: rgba(247, 0, 148, 0.4);
    box-shadow: 0px 4.6666666667px 24px 3px rgba(247, 0, 148, 0.2);
  }
}
@keyframes flash-3 {
  0%, 100% {
    background: #f70094;
    box-shadow: 0px 4.6666666667px 24px 3px #f70094;
  }
  50% {
    background: rgba(247, 0, 148, 0.4);
    box-shadow: 0px 4.6666666667px 24px 3px rgba(247, 0, 148, 0.2);
  }
}
</style>

templates/frontend/components/index/_about.html.twig
<section class="about section-margin pb-xl-70">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xl-6 mb-5 mb-md-0 pb-5 pb-md-0">
                <div class="img-styleBox">
                    <div class="styleBox-border">
                        <img class="styleBox-img1 img-fluid" src="{{ asset('img/map-elizalde.jpg') }}" alt="Marker at Map">
                    </div>
                    <img class="styleBox-img2 img-fluid" src="{{ asset('img/elizalde-bar.jpg') }}" alt="">
                </div>
            </div>
            <div class="col-md-6 pl-md-5 pl-xl-0 offset-xl-1 col-xl-5">
                <div class="section-intro mb-lg-4">
                    <h4 class="intro-title">{% trans %}about.title{% endtrans %}</h4>
                    <h2>{{ text.sobreNosotrosTitulo(_locale)}}</h2>
                </div>
                <p>{{ text.sobreNosotrosTexto(_locale) }}</p>
                <a class="button button-shadow mt-2 mt-lg-4" href="#booking">{% trans %}cta.book_now{% endtrans %}</a>
            </div>
        </div>
    </div>
</section>
<!--================About Section End =================-->

templates/frontend/components/index/_book_section.html.twig
  <!--================Reservation section start =================-->
  <section class="bg-lightGray section-padding">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-6 col-xl-5 mb-4 mb-md-0">
          <div class="section-intro">
            <h4 class="intro-title">{% trans %}book.title{% endtrans %}</h4>
            <h2 class="mb-3">{{ text.reservaTitulo(_locale) }}</h2>
          </div>
          <p>{{ text.reservaTexto(_locale) }}</p>
        </div>

        <div class="col-md-6 offset-xl-2 col-xl-5">
          <div class="bookform-wrapper" style="background-image: url({{asset('img/home/reservation-bg.png')}})">
            <h3>{% trans %}book.form.book_table{% endtrans %}</h3>
            {{ form_start(form, {'attr':{'class': 'bookform-form' } }) }}

              <div class="form-group">
                <div class="input-group">
                  <input type="text" name="{{ form.clientName.vars.full_name }}" class="form-control" placeholder="{% trans %}book.form.name{% endtrans %}" required>
                  <div class="input-group-append">
                    <span class="input-group-text"><i class="ti-user"></i></span>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <input type="email" name="{{ form.clientEmail.vars.full_name }}" class="form-control" placeholder="{% trans %}book.form.email{% endtrans %}" required>
                  <div class="input-group-append">
                    <span class="input-group-text"><i class="ti-email"></i></span>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <input type="text" name="{{ form.telephone.vars.full_name }}" class="form-control" placeholder="{% trans %}book.form.phone_number{% endtrans %}">
                  <div class="input-group-append">
                    <span class="input-group-text"><i class="ti-headphone-alt"></i></span>
                  </div>
                </div>
              </div>

              <div class="row datetime-inputs">
                <div class="form-group col-md-6">
                    <div class="input-group">
                      <input type="date" name="{{ form.bookingDate.vars.full_name }}" class="form-control" placeholder="{% trans %}book.form.select_date{% endtrans %}"
                      min="{{ 'now + 12 hours' | date('Y-m-d') }}" max="{{ 'today + 45 days' | date('Y-m-d') }}"  required>
                      <div class="input-group-append">
                        <span class="input-group-text"><i class="ti-notepad"></i></span>
                      </div>
                    </div>
                  </div>
                  <div class="form-group col-md-6">
                    <div class="input-group">
                      <input type="time" name="{{ form.bookingTime.vars.full_name }}" min="12:00" max="23:00" class="form-control" placeholder="{% trans %}book.form.select_time{% endtrans %}" required>
                      <div class="input-group-append">
                        <span class="input-group-text"><i class="ti-alarm-clock"></i></span>
                      </div>
                    </div>
                  </div>
              </div>


              <div class="form-group">
                <div class="input-group">
                  <input type="number" name="{{ form.peopleCount.vars.full_name }}" class="form-control" placeholder="{% trans %}book.form.select_people{% endtrans %}" required max=40 min=1 >
                  <div class="input-group-append">
                    <span class="input-group-text"><i class="ti-layout-column3"></i></span>
                  </div>
                </div>
              </div>

              <div class="form-group">
                  <div class="input-group">
                    <input type="text" name="{{ form.clientMessage.vars.full_name }}" class="form-control" placeholder="{% trans %}book.form.comentary{% endtrans %}">
                    <div class="input-group-append">
                      <span class="input-group-text"><i class="ti-comment"></i></span>
                    </div>
                  </div>
                </div>
              <div class="form-group form-group-position">
                <button class="button border-0 submit-btn" type="submit">{% trans %}cta.book_now.send{% endtrans %}</button>
              </div>
              {{ form_widget(form._token)}}
              {{ form_widget(form.campaign)}}
              {{ form_widget(form.bookingLang)}}
            </form>
            <div class="alert-msg">

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================Reservation section end =================-->

templates/frontend/components/index/_contact_faq.html.twig
<section class="contact_faq">

    <div class="title title--center">
        <h2>
            {% trans %}
                section_title.contact
            {% endtrans %}
        </h2>
    </div>

    <div class="contact_faq__content">

        <div class="contact_faq__content__faq">
            <h4>
                {% trans %}
                    subtitle.frequently_askly_questions
                {% endtrans %}
            </h4>
            <ul>
                <li>
                    {% trans %}
                        text.question_1
                    {% endtrans %}

                    <p>
                        {% trans %}
                            text.answer_1
                        {% endtrans %}
                        <a href="{{ path('booking') }}">
                            {% trans %}
                                button.reservation_form
                            {% endtrans %}
                        </a>.
                    </p>
                </li>
                <li>
                    {% trans %}
                        text.question_2
                    {% endtrans %}
                    <p>
                        {% trans %}
                            text.answer_2
                        {% endtrans %}
                    </p>
                </li>
                <li>
                    {% trans %}
                        text.question_3
                    {% endtrans %}

                    <p>
                        {% trans %}
                            text.answer_3
                        {% endtrans %}
                    </p>
                </li>
                <li>
                    {% trans %}
                        text.question_4
                    {% endtrans %}
                    <p>
                        {% trans %}
                            text.answer_4
                        {% endtrans %}
                        <a target="_self" href="{{ path('booking') }}">
                            {% trans %}
                                button.reservation_form
                            {% endtrans %}
                        </a>.
                    </p>
                </li>
            </ul>
        </div>

        <div class="contact_faq__content__contact">
            <h4>
                {% trans %}
                    subtitle.send_message
                {% endtrans %}
            </h4>
            {{ form(form) }}
        </div>
    </div>
</section>

templates/frontend/components/index/_contact_section.html.twig
  <!--================Reservation section start =================-->  
  <section class="bg-lightGray smallSection contact" style="background-image: url({{asset('img/wall.jpg')}})">
    <img src="{{asset('img/icons/restaurant-cutlery.svg')}}" class="contact-icon">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-6 col-xl-5 mb-4 mb-md-0">
          
          <div class="section-intro">
            <h4 class="intro-title">{% trans %}contact.title{% endtrans %}</h4>
          </div>
          <p>{% trans %}contact.text{% endtrans %}</p>
        </div>
        <div class="col-md-6 offset-xl-2 col-xl-5">
          <div class="section-intro">
              <ul>
                  <li>
                    <i class="ti-map"></i>
                    {% trans %}contact.address{% endtrans %}
                  </li>
                  <li>
                    <i class="ti-mobile"></i>
                    <a href="tel://+5378672157">(+53) 7 867 2157</a>
                  </li>
                  <li>
                      <i class="ti-email"></i>
                      <a href="mailto:elizaldebarrestaurante@gmail.com">elizaldebarrestaurante@gmail.com</a>
                  </li>
                  <li>
                      <i class="ti-alarm-clock"></i>{% trans %}contact.hours.open{% endtrans %}
                  </li>
              </ul>
            
        </div>
      </div>
    </div>
  </section>
  <!--================Reservation section end =================-->  

templates/frontend/components/index/_cta_home_section.html.twig
  <!--================CTA section start =================-->  
  <section class="cta-area text-center" style="background-image: url({{asset('img/frontal-wide-001.jpg')}});">
    <div class="container">
      <p>{% trans %}home.cta.text{% endtrans %}</p>
      <h2>{% trans %}home.cta.bigtext{% endtrans %}</h2>
      <a class="button" href="#booking">{% trans %}cta.book_now{% endtrans %}</a>
    </div>
  </section>
  <!--================CTA section end =================-->  

templates/frontend/components/index/_featured_food.html.twig
{% if featuresFoodList %}
<!--================Featured Section Start =================-->
<section class="section-margin mb-lg-100">
    <div class="container">
        <div class="section-intro mb-75px">
            <h4 class="intro-title">{% trans %}food.title{% endtrans %}</h4>
            <h2>{% trans %}food.subtitle{% endtrans %}</h2>
        </div>
        <div class="owl-carousel owl-theme featured-carousel">
            {% for featuredFood in featuresFoodList %}

                <div class="featured-item">
                    <img class="card-img rounded-0" style="max-height: 20rem" src="{{ asset(featuredFood.imagePath) }}" alt="{{ featuredFood.Translations(_locale).name }}">
                    <div class="item-body">
                        <a href="#">
                            <h3>{{ featuredFood.Translations.name }}</h3>
                        </a>
                        <p>{{ featuredFood.Translations.ingredients }}</p>
                        <div class="d-flex justify-content-between">
                            <ul class="rating-star">
                                <li><i class="ti-star"></i></li>
                                <li><i class="ti-star"></i></li>
                                <li><i class="ti-star"></i></li>
                                <li><i class="ti-star"></i></li>
                                <li><i class="ti-star"></i></li>
                            </ul>
                            {% if featuredFood.price %}
                                <h3 class="price-tag">${{ featuredFood.price }}</h3>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
<!--================Featured Section End =================-->
{% endif %}

templates/frontend/components/index/_hero.html.twig
<!--================Hero Banner Section start =================-->
<section class="hero-banner">
    <div class="hero-wrapper">
        <div class="hero-left">
            <h1 class="hero-title">{{ text.tituloPrincipal(_locale)}}
                <br>
                <small>{{ text.subtituloPrincipal(_locale) }}</small> </h1>
            <div class="d-sm-flex flex-wrap">
                <a class="button button-hero button-shadow" href="#booking">{% trans %}cta.book_now{% endtrans %}</a>
                <a class="hero-banner__video" href="{{ text.videoLink }}">
                    <img src="{{ asset('img/icons/play.png') }}" alt="{% trans %}hero.see_video{% endtrans %}">
                    {% trans %}hero.see_video{% endtrans %}
                </a>
            </div>
            <ul class="hero-info d-none d-lg-block">
                {#<li>#}
                    {#<img src="img/banner/fas-service-icon.png" alt="">#}
                    {#<h4>Fast Service</h4>#}
                {#</li>#}
                {#<li>#}
                    {#<img src="img/banner/fresh-food-icon.png" alt="">#}
                    {#<h4>Fresh Food</h4>#}
                {#</li>#}
                {#<li>#}
                    {#<img src="img/banner/support-icon.png" alt="">#}
                    {#<h4>24/7 Support</h4>#}
                {#</li>#}
            </ul>
        </div>
        <div class="hero-right">
            <div class="owl-carousel owl-theme hero-carousel">


              {% for image in images %}
            	  <div class="hero-carousel-item animated-img-container">
                    <img class="img-fluid" src="{{ asset(image.imagePath)}}" alt="" style="max-height: 85vh;width: auto;">
                    <a class="button button-hero button-shadow" href="{{ asset(image.imagePath)}}">+</a>

                </div>
              {% endfor %}

            </div>
        </div>
        <ul class="social-icons d-none d-lg-block">
            <li>
                <a href="https://www.facebook.com/ElizaldeHabana/" target="_blank">
                    {{ source('svg/facebook.svg') }}
                </a>
            </li>
            <li>
                <a href="http://www.tripadvisor.com/Restaurant_Review-d12580283" target="_blank">
                    {{ source('svg/tripadvisor.svg') }}
                </a>
            </li>
            <li>
                {# TODO: LINK To instagram#}
                <a href="https://instagram.com/elizaldehabana/">
                        {{ source('svg/instagram.svg') }}
                </a>
            </li>
            <li>
                <a href="mailto:elizaldebarrestaurante@gmail.com">
                        {{ source('svg/mail.svg') }}
                </a>
            </li>

        </ul>
        {{ source('svg/wave01.svg') }}
        {{ source('svg/wave02.svg') }}
        <style type="text/css">
        	.section-wave.hero-wave{position: absolute;bottom: 0;width: 100%;left: 0;z-index: -1}
        </style>
    </div>
</section>
<!--================Hero Banner Section end =================-->

templates/frontend/components/index/_offer.html.twig
{% if offer %}
<!--================Offer Section Start =================-->
<section class="bg-lightGray section-padding">
    <div class="container">
        <div class="row no-gutters">
            <div class="col-sm">
                <img class="card-img rounded-0" src="{{ asset(offer.imagePath)}}" alt="">
            </div>
            <div class="col-sm">
                <div class="offer-card offer-card-position">
                    <h3>{{ offer.title(_locale) }}</h3>
                    <h2>{{ offer.text(_locale) }}</h2>
                    <b>{% trans %}offer.cta.btn_text{% endtrans %}</b>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================Offer Section End =================-->
{% endif %}